apis: []
blockchain:
  auto_deploy: true
  network: bsc-testnet
monitoring:
  dashboard_port: 8080
  enabled: true
prfi:
  fallback:
    auto_discover: true
    enabled: true
  retry:
    initial_delay: 1.0
    jitter: true
    max_attempts: 5
    max_delay: 300.0
    multiplier: 2.0
  tokenization:
    enabled: true
    min_difficulty: 4
project:
  description: Projeto PRFI gerado automaticamente
  name: meu-projeto-prfi
  version: 1.0.0
